# -------------------------------------
# Copyright (c) 2026, Dror Kabely
# -------------------------------------
#

load("@//tools/testing:pytest.bzl", py_test = "pytest_test")
load("@pip//:requirements.bzl", "requirement")
load("@rules_python//python:defs.bzl", "py_library")

package(
    default_visibility = ["//visibility:private"],
)

py_library(
    name = "conftest",
    testonly = True,
    srcs = ["conftest.py"],
    visibility = ["//:__subpackages__"],
    deps = [
        "//tests/lib/testcontainers/vllm:pkg",
        requirement("pytest"),
        requirement("testcontainers"),
    ],
)

py_test(
    name = "test_late_interaction",
    srcs = ["test_late_interaction.py"],
    env = {
        "TC_MAX_TRIES": "1000000000",
    },
    tags = [
        "integration",
        "local",
    ],
    deps = [
        ":conftest",
        "//src/lib/core/adapters/embedding:pkg",
        requirement("httpx"),
        requirement("pytest"),
        requirement("pytest-asyncio"),
    ],
)
