load("@//tools/testing:pytest.bzl", py_test = "pytest_test")
load("@aspect_rules_py//py:defs.bzl", "py_library")
load("@pip//:requirements.bzl", "requirement")

py_library(
    name = "conftest",
    testonly = True,
    srcs = ["conftest.py"],
    deps = [
        requirement("httpx"),
        requirement("pytest"),
        requirement("testcontainers"),
        requirement("wiremock"),
    ],
)

py_test(
    name = "test_init_contract",
    srcs = ["test_init_contract.py"],
    tags = ["integration"],
    deps = [
        ":conftest",
        requirement("httpx"),
        requirement("pytest"),
    ],
)
