load("@//tools/testing:pytest.bzl", py_test = "pytest_test")
load("@pip//:requirements.bzl", "requirement")

py_test(
    name = "test_tasks",
    srcs = ["test_tasks.py"],
    deps = [
        "//src/backend/controller/worker:exceptions",
        "//src/backend/controller/worker:tasks",
        "//src/lib/core/ingestion:types",
        "//tests/backend/controller/worker:conftest",
        requirement("pytest"),
    ],
)

py_test(
    name = "test_parse_tasks",
    srcs = ["test_parse_tasks.py"],
    tags = ["unit"],
    deps = [
        "//src/backend/controller/worker:tasks",
        "//src/backend/controller/worker/backend:claims",
        "//tests/backend/controller/worker:conftest",
        requirement("httpx"),
        requirement("pybreaker"),
        requirement("pytest"),
        requirement("sqlalchemy"),
    ],
)
