load("@//tools/testing:pytest.bzl", py_test = "pytest_test")
load("@aspect_rules_py//py:defs.bzl", "py_library")
load("@pip//:requirements.bzl", "requirement")

py_library(
    name = "pkg",
    srcs = ["__init__.py"],
    visibility = ["//visibility:public"],
)

py_library(
    name = "conftest",
    srcs = ["conftest.py"],
    visibility = ["//visibility:public"],
    deps = [
        "//tests/lib/testcontainers:migrations",
        requirement("fastapi"),
        requirement("httpx"),
        requirement("pytest"),
        requirement("testcontainers"),
        requirement("wiremock"),
    ],
)

py_test(
    name = "test_dedup",
    size = "large",
    srcs = ["test_dedup.py"],
    tags = [
        "container",
        "integration",
        "local",  # disable Bazel sandbox so Docker volume mounts see the real host filesystem
    ],
    deps = [
        ":conftest",
        requirement("fastapi"),
        requirement("httpx"),
        requirement("pytest"),
    ],
)
