name: venus-ingestion
x-minio-common: &minio-common
  image: quay.io/minio/minio:RELEASE.2025-04-22T22-12-26Z
  command: server --console-address ":9090" /mnt/data
  expose:
    - "9000"
    - "9090"
  ports:
    - 9000:9000
    - 10090:9090
  environment:
    MINIO_ROOT_USER: minioadmin
    MINIO_ROOT_PASSWORD: minioadmin
    MINIO_VOLUMES: "/mnt/data"
  healthcheck:
    test: ["CMD", "mc", "ready", "local"]
    interval: 5s
    timeout: 5s
    retries: 5
services:
  # embedding model
  tei:
    image: ghcr.io/huggingface/text-embeddings-inference:86-1.5  # RTX 3090 is an Ampere 86 card
    restart: no
    expose:
      - 80
    volumes:
      - /ckpts/.tei:/data
    command: --model-id "sentence-transformers/msmarco-MiniLM-L-12-v3"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
  db:
    image: postgres:14-alpine
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: &database_password ${DATABASE_PASSWORD}
      POSTGRES_USER: &database_user ${DATABASE_USERNAME:-postgres}
      POSTGRES_DB: &database_name ${DATABASE_NAME:-ingestion}
  vectorstore:
    image: qdrant/qdrant:v1.13.6-unprivileged
    expose:
      - "6333"
      - "6334"
    ports:
      - 6333:6333
  docling-inference:
    image: ghcr.io/aidotse/docling-inference:latest
    expose:
      - 8080
    environment:
      - NUM_WORKERS=1
    volumes:
      - hf_cache:/root/.cache/huggingface
      - ocr_cache:/root/.EasyOCR
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  docling-serve:
    image: ghcr.io/docling-project/docling-serve-cu124
    expose:
      - 5001
    ports:
      - 5001:5001
    environment:
      - NUM_WORKERS=1
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
  # Kafka broker for streaming the following events:
  #
  # 1. Stored 
  broker:
    image: apache/kafka:4.0.0
    hostname: broker
    container_name: broker
    expose:
      - "9092"
      - "9097"
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://broker:29092,EXTERNAL://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@broker:29093
      KAFKA_LISTENERS: INTERNAL://broker:29092,CONTROLLER://broker:29093,EXTERNAL://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LOG_DIRS: /tmp/kraft-combined-logs
      KAFKA_CREATE_TOPICS: "_connect-status,_connect-offsets,_connect-configs"
      KAFKA_JMX_PORT: "9997"
      CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk
  schemaregistry:
    image: confluentinc/cp-schema-registry:6.0.0
    restart: always
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schemaregistry
      SCHEMA_REGISTRY_LISTENERS: "http://schemaregistry:8081"
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: PLAINTEXT://broker:29092
    ports:
      - 8081:8081
  kafka-connect:
    image: venus/cp-kafka-connect:latest
    container_name: kafka-connect
    depends_on:
      - broker
      - schemaregistry
    ports:
      - 8083:8083
    environment:
      CONNECT_BOOTSTRAP_SERVERS: "broker:29092"
      CONNECT_REST_PORT: 8083
      CONNECT_GROUP_ID: kafka-connect
      CONNECT_CONFIG_STORAGE_TOPIC: _connect-configs
      CONNECT_OFFSET_STORAGE_TOPIC: _connect-offsets
      CONNECT_STATUS_STORAGE_TOPIC: _connect-status
      CONNECT_KEY_CONVERTER: org.apache.kafka.connect.storage.StringConverter
      CONNECT_VALUE_CONVERTER: org.apache.kafka.connect.storage.StringConverter
      CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL: 'http://schemaregistry:8081'
      CONNECT_REST_ADVERTISED_HOST_NAME: "kafka-connect"
      CONNECT_LOG4J_APPENDER_STDOUT_LAYOUT_CONVERSIONPATTERN: "[%d] %p %X{connector.context}%m (%c:%L)%n"
      CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: "1"
      CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: "1"
      CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: "1"
    #  ---------------
      CONNECT_PLUGIN_PATH: /usr/share/java,/usr/share/confluent-hub-components,/data/connect-jars
  kafka-connect-init:
    image: venus/cp-kafka-connect-init:latest
    environment:
      KAFKA_CONNECT_CLUSTER_URI: http://kafka-connect:8083
  httpmockserver:
    image: mockserver/mockserver
    ports:
      - 11111:8080
    expose:
      - "8080"
    volumes:
      - ./initializerJson.json:/config/initializerJson.json
      - ./mockserver.properties:/config/mockserver.properties
    environment:
      MOCKSERVER_SERVER_PORT: "8080"
      MOCKSERVER_LOG_LEVEL: "TRACE"
      MOCKSERVER_INITIALIZATION_JSON_PATH: /config/initializerJson.json
      MOCKSERVER_PROPERTY_FILE: /config/mockserver.properties
  kafkacat:
    image: confluentinc/cp-kafkacat
    command: sleep infinity
  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - 18080:8080
    depends_on:
      - broker
      - schemaregistry
      - kafka-connect
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: broker:29092
      KAFKA_CLUSTERS_0_METRICS_PORT: 9997
      KAFKA_CLUSTERS_0_SCHEMAREGISTRY: http://schemaregistry:8081
      KAFKA_CLUSTERS_0_KAFKACONNECT_0_NAME: first
      KAFKA_CLUSTERS_0_KAFKACONNECT_0_ADDRESS: http://kafka-connect:8083
      DYNAMIC_CONFIG_ENABLED: 'true'
  # S3 compatible storage
  minio:
    <<: *minio-common
    hostname: minio
    environment:
      MINIO_NOTIFY_KAFKA_ENABLE_VENUS: "on"
      MINIO_NOTIFY_KAFKA_BROKERS_VENUS: broker:29092
      MINIO_NOTIFY_KAFKA_TOPIC_VENUS: venus.ingestion.storage.s3
      MINIO_NOTIFY_KAFKA_ENABLE_TEST_ANOTHER: "on"
      MINIO_NOTIFY_KAFKA_BROKERS_TEST_ANOTHER: broker:29092
      MINIO_NOTIFY_KAFKA_TOPIC_TEST_ANOTHER: venus.test.upload.s3
    volumes:
      - minio-data-1:/mnt/data
  backend:
    image: celery-ingestion/backend:latest
    depends_on:
      - db
      - docling-inference
      - vectorstore
      - tei
    restart: on-failure:10  # to compensate TEI model download time
    environment:
      DATABASE_HOSTNAME: db
      DATABASE_PORT: ${DATABASE_PORT:-5432}
      DATABASE_USERNAME: *database_user
      POSTGRES_PASSWORD: *database_password
      DATABASE_NAME: *database_name
      TEI_HOST_URL: "http://tei/"
      DOCLING_BACKEND_URL: http://docling-inference:8080/
      QDRANT_HOST_URL: http://vectorstore/
      QDRANT_HOST_PORT: "6333"
      QDRANT_COLLECTION_NAME: "venus"
    ports:
      - 9002:9002
  backend-storage:
    image: venus/backend:latest
    depends_on:
      - minio
    environment:
      S3_ENDPOINT_URL: minio:9000
      S3_ACCESS_KEY: minioadmin
      S3_SECRET_KEY: minioadmin
      S3_VENUS_BUCKET: venus
      S3_VENUS_BUCKET_KAFKA_EVENT: VENUS
    expose:
      - "9093"
    ports:
      - 19094:9093

volumes:
  db-data:
  hf_cache:
  ocr_cache:
  docling:
  minio-data-1: