name: venus-ingestion
services:
  # embedding model
  tei:
    image: ghcr.io/huggingface/text-embeddings-inference:86-1.5  # RTX 3090 is an Ampere 86 card
    restart: no
    expose:
      - 80
    volumes:
      - /ckpts/.tei:/data
    command: --model-id "sentence-transformers/msmarco-MiniLM-L-12-v3"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
  db:
    image: postgres:14-alpine
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: &database_password ${DATABASE_PASSWORD}
      POSTGRES_USER: &database_user ${DATABASE_USERNAME:-postgres}
      POSTGRES_DB: &database_name ${DATABASE_NAME:-ingestion}
  vectorstore:
    image: qdrant/qdrant:v1.13.6-unprivileged
    expose:
      - 6333
    ports:
      - 6333:6333
  backend:
    image: celery-ingestion/backend:latest
    depends_on:
      - db
      - docling-inference
      - vectorstore
      - tei
    restart: on-failure:10  # to compensate TEI model download time
    environment:
      DATABASE_HOSTNAME: db
      DATABASE_PORT: ${DATABASE_PORT:-5432}
      DATABASE_USERNAME: *database_user
      POSTGRES_PASSWORD: *database_password
      DATABASE_NAME: *database_name
      TEI_HOST_URL: "http://tei/"
      DOCLING_BACKEND_URL: http://docling-inference:8080/
      QDRANT_HOST_URL: http://vectorstore/
      QDRANT_HOST_PORT: "6333"
      QDRANT_COLLECTION_NAME: "venus"
    ports:
      - 9002:9002
  docling-inference:
    image: ghcr.io/aidotse/docling-inference:latest
    expose:
      - 8080
    environment:
      - NUM_WORKERS=1
    volumes:
      - hf_cache:/root/.cache/huggingface
      - ocr_cache:/root/.EasyOCR
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  docling-serve:
    image: ghcr.io/docling-project/docling-serve-cu124
    expose:
      - 5001
    ports:
      - 5001:5001
    environment:
      - NUM_WORKERS=1
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
volumes:
  db-data:
  hf_cache:
  ocr_cache:
  docling: