load("@//tools/testing:pytest.bzl", py_test = "pytest_test")
load("@pip//:requirements.bzl", "requirement")

py_test(
    name = "test_parsed_chunks",
    srcs = ["test_parsed_chunks.py"],
    tags = ["unit"],
    deps = [
        "//src/lib/core/adapters/stores/minio:parsed_chunks",
        "//src/lib/core/ingestion:types",
        requirement("pytest"),
    ],
)
