load("@aspect_rules_py//py:defs.bzl", "py_library")
load("@pip//:requirements.bzl", "requirement")

package(default_visibility = [
    "//src/backend/alembic:__pkg__",
    "//src/backend/controller/worker:__subpackages__",
    "//tests/backend/controller/worker:__subpackages__",
])

py_library(
    name = "pkg",
    srcs = ["__init__.py"],
    deps = [
        ":claims",
        ":db",
        ":outbox",
    ],
)

py_library(
    name = "db",
    srcs = [
        "db.py",
    ],
    deps = [
        requirement("sqlalchemy"),
        "//src/backend/controller/worker:config",
    ],
)

py_library(
    name = "claims",
    srcs = [
        "claims.py",
    ],
    deps = [
        requirement("pydantic"),
        requirement("sqlalchemy"),
        "//src/backend/controller/lib:schemas",
        "//src/lib/backend/db:base",
    ],
)

py_library(
    name = "outbox",
    srcs = [
        "outbox.py",
    ],
    deps = [
        requirement("sqlalchemy"),
        "//src/lib/backend/db:base",
    ],
)
