load("@aspect_rules_py//py:defs.bzl", "py_library")
load("@pip//:requirements.bzl", "requirement")

package(default_visibility = [
    "//src/backend/alembic:__pkg__",
    "//src/backend/controller/worker:__subpackages__",
    "//tests/backend/controller/worker:__subpackages__",
])

py_library(
    name = "pkg",
    srcs = ["__init__.py"],
    deps = [
        ":claims",
        ":database",
    ],
)

py_library(
    name = "database",
    srcs = [
        "database.py",
    ],
    deps = [
        requirement("vine"),
        requirement("celery"),
        requirement("sqlalchemy"),
        ":models",
    ],
)

py_library(
    name = "claims",
    srcs = [
        "claims.py",
    ],
    deps = [
        requirement("pydantic"),
        requirement("sqlalchemy"),
        "//src/backend/controller/lib:schemas",
        "//src/lib/backend/db:base",
    ],
)

py_library(
    name = "models",
    srcs = [
        "models.py",
    ],
    deps = [
        requirement("sqlalchemy"),
        requirement("celery"),
    ],
)
