# -------------------------------------
# Copyright (c) 2025, Dror Kabely
# -------------------------------------
#
# gazelle:python_root

load("@aspect_bazel_lib//lib:transitions.bzl", "platform_transition_filegroup")
load("@aspect_bazel_lib//lib:tar.bzl", "tar", "mtree_spec", "mtree_mutate")
load("@aspect_bazel_lib//lib:testing.bzl", "assert_archive_contains")
load("@rules_oci//oci:defs.bzl", oci_load = "oci_tarball", "oci_push")
load("@aspect_rules_py//py:defs.bzl", "py_binary", "py_library")
load("@pip//:requirements.bzl", "requirement")

load("//tools/oci:py_layer.bzl", "py_oci_image")
load("//tools/server:uvicorn.bzl", "uvicorn_dev_server")
load("//tools/server:celery.bzl", "celery_worker")

package(default_visibility = ["//src/backend/storage/api:__subpackages__"])

# Equivalent to cmdline:
#  `uvicorn main:app --host localhost --port 9002`
uvicorn_dev_server(
    name = "server",
    args = [
        "main:app",
        "--host",
        "localhost",
        "--port",
        "7000",
        "--reload",
    ],
    imports = ["."],
    visibility = ["//visibility:public"],
    deps = [
        ":pkg",
    ],
)

py_library(
    name = "pkg",
    srcs = [
        "__init__.py",
    ],
    deps = [
        ":main",
    ]
)

API_ROUTER_PKGS = [
    "//src/backend/storage/api/private:pkg",
    "//src/backend/storage/api/health:pkg",
]

py_library(
    name = "main",
    srcs = [
        "main.py",
    ],
    deps = [
        ":config",
        ":exceptions",
        ":utils",
        requirement("fastapi"),
    ] + API_ROUTER_PKGS,
)

py_library(
    name = "exceptions",
    srcs = [
        "exceptions.py",
    ],
    deps = [
        "//src/backend/storage/api/private:exceptions",
        requirement("fastapi"),
    ]
)

py_library(
    name = "dependencies",
    srcs = [
        "dependencies.py",
    ],
    deps = [
        ":config",
        requirement("fastapi"),
        requirement("minio"),
    ],
)

py_library(
    name = "utils",
    srcs = [
        "utils.py",
    ],
    deps = [
        ":config",
        ":dependencies",
        requirement("fastapi"),
        requirement("minio"),
    ]
)

py_library(
    name = "config",
    srcs = [
        "config.py",
    ],
    deps = [
        requirement("pydantic"),
        requirement("pydantic-settings"),
    ],
)

# OCI Image for Storage service

py_oci_image(
    name = "image",
    base = "@ubuntu",
    binary = ":server",
    entrypoint = [
        "/src/backend/storage/api/server",
        "main:app",
        "--host",
        "0.0.0.0",  # this should allow connections from host
        "--port",
        "7000",
    ],
    exposed_ports = ["7000"],
    visibility = ["//src/backend:__pkg__"],
)

# $ bazel run //src/backend/indexing/api:tarball
oci_load(
    name = "image.tarball",
    image = ":image",
    repo_tags = ["venus/backend-storage:latest"],
)