# -------------------------------------
# Copyright (c) 2025, Dror Kabely
# -------------------------------------
#
# gazelle:python_root

load("@aspect_rules_py//py:defs.bzl", "py_library")
load("@pip//:requirements.bzl", "requirement")

# load("@aspect_bazel_lib//lib:transitions.bzl", "platform_transition_filegroup")
# load("@aspect_bazel_lib//lib:tar.bzl", "tar", "mtree_spec", "mtree_mutate")
# load("@aspect_bazel_lib//lib:testing.bzl", "assert_archive_contains")
load("@rules_oci//oci:defs.bzl", oci_load = "oci_tarball")
load("//tools/backend:uvicorn.bzl", "uvicorn_server")
# load("//tools/server:celery.bzl", "celery_worker")

load("//tools/oci:py_layer.bzl", "py_oci_image")
load("//tools/oci:stamped_tags.bzl", "stamped_tags")

package(
    default_visibility = [
        "//src/backend/alembic:__subpackages__",
        "//src/backend/storage/api:__subpackages__",
        "//tests/backend/storage/api:__subpackages__",
        "//tests/oci:__subpackages__",
        "//tests/subsystem:__subpackages__",
    ],
)

STORAGE_SERVICE_PORT = "7000"

# Equivalent to cmdline:
uvicorn_server(
    name = "server",
    app = "src.backend.storage.api.main:app",
    host = "0.0.0.0",
    port = STORAGE_SERVICE_PORT,
    deps = [
        ":pkg",
    ],
)

py_library(
    name = "pkg",
    srcs = [
        "__init__.py",
    ],
    deps = [
        ":main",
    ],
)

API_ROUTER_PKGS = [
    "//src/backend/storage/api/health:pkg",
    "//src/backend/storage/api/namespaces:pkg",
    "//src/backend/storage/api/files:pkg",
]

py_library(
    name = "main",
    srcs = [
        "main.py",
    ],
    deps = [
        ":exceptions",
        ":utils",
        "//src/backend/storage/api/files:exceptions",
        "//src/backend/storage/api/namespaces:exceptions",
        "//src/lib/backend/api:exceptions",
        "//src/lib/backend/telemetry:pkg",
        requirement("opentelemetry-instrumentation-fastapi"),
        requirement("opentelemetry-instrumentation-httpx"),
        requirement("opentelemetry-instrumentation-sqlalchemy"),
        requirement("fastapi"),
    ] + API_ROUTER_PKGS,
)

py_library(
    name = "exceptions",
    srcs = [
        "exceptions.py",
    ],
    deps = [
        requirement("fastapi"),
    ],
)

py_library(
    name = "models",
    srcs = [
        "models.py",
    ],
    deps = [
        "//src/lib/backend/db:base",
        requirement("sqlalchemy"),
    ],
)

py_library(
    name = "dependencies",
    srcs = [
        "dependencies.py",
    ],
    deps = [
        ":config",
        "//src/lib/backend/db:session",
        requirement("fastapi"),
        requirement("minio"),
        requirement("sqlalchemy"),
    ],
)

py_library(
    name = "utils",
    srcs = [
        "utils.py",
    ],
    deps = [
        ":config",
        ":dependencies",
        ":models",
        "//src/lib/backend/db:session",
        "//src/lib/backend/logging:pkg",
        requirement("fastapi"),
        requirement("minio"),
        requirement("sqlalchemy"),
    ],
)

py_library(
    name = "tombstone",
    srcs = [
        "tombstone.py",
    ],
    deps = [
        ":models",
        ":service",
        "//src/lib/core/ingestion:contract",
        requirement("minio"),
        requirement("sqlalchemy"),
    ],
)

py_library(
    name = "service",
    srcs = [
        "service.py",
    ],
    deps = [
        ":exceptions",
        ":models",
        requirement("sqlalchemy"),
    ],
)

py_library(
    name = "config",
    srcs = [
        "config.py",
    ],
    deps = [
        requirement("pydantic"),
        requirement("pydantic-settings"),
        requirement("asyncpg"),
    ],
)

# OCI Image for Storage service

py_oci_image(
    name = "image",
    base = "@ubuntu",
    binary = ":server.dev",
    entrypoint = [
        "/src/backend/storage/api/server.dev",
        "src.backend.storage.api.main:app",
        "--host",
        "0.0.0.0",
        "--port",
        STORAGE_SERVICE_PORT,
    ],
    exposed_ports = [STORAGE_SERVICE_PORT],
    visibility = ["//src/backend:__pkg__"],
)

# $ bazel run //src/backend/storage/api:tarball.dev
# Release: $ bazel run //src/backend/storage/api:tarball.dev --stamp
stamped_tags(
    name = "tarball.dev.tags",
    dev_tags = ["dev"],
    repository = "artemis/backend-storage",
)

oci_load(
    name = "tarball.dev",
    image = ":image",
    repo_tags = ":tarball.dev.tags",
    visibility = [
        "//src:__pkg__",
    ],
)
