load("@//tools/testing:pytest.bzl", py_test = "pytest_test")
load("@aspect_rules_py//py:defs.bzl", "py_library")
load("@pip//:requirements.bzl", "requirement")

py_library(
    name = "conftest",
    testonly = True,
    srcs = ["conftest.py"],
    deps = [
        "//tests/lib/testcontainers:migrations",
        "//tests/lib/testcontainers/tei:pkg",
        "//tests/lib/testcontainers/vllm:pkg",
        requirement("asyncpg"),
        requirement("httpx"),
        requirement("minio"),
        requirement("pytest"),
        requirement("qdrant-client"),
        requirement("testcontainers"),
    ],
)

py_test(
    name = "test_smoke",
    srcs = ["test_smoke.py"],
    data = ["//src/backend/alembic:tarball.dev"],
    env = {"TC_MAX_TRIES": "1000000000"},
    tags = ["local"],
    deps = [
        ":conftest",
        requirement("httpx"),
        requirement("minio"),
        requirement("pytest"),
        requirement("pytest-asyncio"),
        requirement("qdrant-client"),
    ],
)

py_test(
    name = "test_parent_page",
    srcs = ["test_parent_page.py"],
    data = ["//src/backend/alembic:tarball.dev"],
    env = {"TC_MAX_TRIES": "1000000000"},
    tags = ["local"],
    deps = [
        ":conftest",
        requirement("httpx"),
        requirement("minio"),
        requirement("pytest"),
        requirement("pytest-asyncio"),
        requirement("qdrant-client"),
    ],
)
