load("@//tools/testing:pytest.bzl", py_test = "pytest_test")
load("@aspect_rules_py//py:defs.bzl", "py_library")
load("@pip//:requirements.bzl", "requirement")

py_library(
    name = "pkg",
    srcs = ["__init__.py"],
    visibility = ["//visibility:public"],
)

py_library(
    name = "conftest",
    testonly = True,
    srcs = ["conftest.py"],
    visibility = ["//visibility:public"],
    deps = [
        "//tests/lib/testcontainers/kafka:pkg",
        requirement("httpx"),
        requirement("kafka-python-ng"),
        requirement("pytest"),
        requirement("testcontainers"),
        requirement("wiremock"),
    ],
)

py_test(
    name = "test_kafka_connect",
    srcs = ["test_kafka_connect.py"],
    tags = [
        "container",
        "integration",
        "local",
    ],
    deps = [
        ":conftest",
        "//tests/lib/testcontainers/kafka:pkg",
        requirement("httpx"),
        requirement("kafka-python-ng"),
        requirement("kafka-connect-py"),
        requirement("pytest"),
        requirement("wiremock"),
    ],
)
