load("@//tools/testing:pytest.bzl", py_test = "pytest_test")
load("@aspect_rules_py//py:defs.bzl", "py_library")
load("@pip//:requirements.bzl", "requirement")

py_library(
    name = "conftest",
    srcs = ["conftest.py"],
    visibility = ["//visibility:public"],
    deps = [
        requirement("pytest"),
        requirement("qdrant-client"),
        requirement("testcontainers"),
    ],
)

py_test(
    name = "test_checks",
    srcs = ["test_checks.py"],
    deps = [
        ":conftest",
        "//src/backend/indexing/api/health:checks",
        requirement("aiohttp"),
        requirement("httpx"),
        requirement("pytest"),
        requirement("pytest-asyncio"),
        requirement("qdrant-client"),
        requirement("respx"),
    ],
)
