# -------------------------------------
# Copyright (c) 2026, Dror Kabely
# -------------------------------------

load("@aspect_rules_py//py:defs.bzl", "py_library")
load("@pip//:requirements.bzl", "requirement")

package(
    default_visibility = [
        "//src/backend/alembic:__subpackages__",
        "//src/backend/enterprise/intake/api:__pkg__",
        "//tests/backend/enterprise/intake:__subpackages__",
    ],
)

py_library(
    name = "pkg",
    srcs = ["__init__.py"],
    deps = [":router"],
)

py_library(
    name = "router",
    srcs = ["router.py"],
    deps = [
        ":schemas",
        ":service",
        "//src/backend/enterprise/intake/api:dependencies",
        "//src/lib/backend/logging:pkg",
        requirement("fastapi"),
    ],
)

py_library(
    name = "service",
    srcs = ["service.py"],
    deps = [
        ":dedup",
        ":exceptions",
        ":schemas",
        "//src/backend/enterprise/intake/api:config",
        requirement("fastapi"),
        requirement("httpx"),
        requirement("filetype"),
        requirement("sqlalchemy"),
    ],
)

py_library(
    name = "models",
    srcs = ["models.py"],
    deps = [
        "//src/lib/backend/db:base",
        requirement("sqlalchemy"),
    ],
)

py_library(
    name = "dedup",
    srcs = ["dedup.py"],
    deps = [
        ":models",
        requirement("sqlalchemy"),
    ],
)

py_library(
    name = "exceptions",
    srcs = ["exceptions.py"],
    deps = [
        requirement("fastapi"),
    ],
)

py_library(
    name = "schemas",
    srcs = ["schemas.py"],
    deps = [
        requirement("pydantic"),
    ],
)
