load("@aspect_bazel_lib//lib:tar.bzl", "tar")
load("@aspect_rules_py//py:defs.bzl", "py_binary", "py_library")
load("@pip//:requirements.bzl", "requirement")
load("@rules_oci//oci:defs.bzl", "oci_image", oci_load = "oci_tarball")  #@unused
load("@rules_python//python/entry_points:py_console_script_binary.bzl", "py_console_script_binary")  #@unused
load("//tools/oci:py_layer.bzl", "py_oci_image")

package(
    default_visibility = [
        "//src:__subpackages__",
        "//src/backend/controller:__subpackages__",
        "//tests/backend/controller:__subpackages__",
    ],
)

tar(
    name = "srcs",
    srcs = [
        "celery.py",
        "config.py",
        "dependencies.py",
        "tasks.py",
    ],
)

py_library(
    name = "pkg",
    srcs = ["__init__.py"],
    deps = [
        ":celery",
        ":config",
        ":dependencies",
        ":tasks",
    ],
)

py_library(
    name = "exceptions",
    srcs = ["exceptions.py"],
)

py_library(
    name = "utils",
    srcs = ["utils.py"],
    deps = [
        ":dependencies",
        "//src/backend/controller/lib:schemas",
        "//src/lib/core/ingestion:types",
        requirement("httpx"),
        requirement("minio"),
        requirement("opentelemetry-api"),
        requirement("pydantic"),
        requirement("pybreaker"),
    ],
)

py_library(
    name = "tasks",
    srcs = ["tasks.py"],
    deps = [
        ":celery",
        ":config",
        ":dependencies",
        ":exceptions",
        ":utils",
        "//src/backend/controller/lib:schemas",
        "//src/backend/controller/worker/backend:pkg",
        "//src/lib/backend/telemetry:pkg",
        "//src/lib/core/adapters/stores/minio:parsed_chunks",
        requirement("psycopg"),
        requirement("psycopg-binary"),
        requirement("celery"),
        requirement("pybreaker"),
    ],
)

py_library(
    name = "celery",
    srcs = ["celery.py"],
    deps = [
        ":config",
        "//src/lib/backend/telemetry:pkg",
        requirement("celery"),
        requirement("opentelemetry-instrumentation-celery"),
        requirement("opentelemetry-instrumentation-httpx"),
        requirement("opentelemetry-instrumentation-sqlalchemy"),
        requirement("psycopg-binary"),
        requirement("sqlalchemy"),
    ],
)

py_library(
    name = "dependencies",
    srcs = ["dependencies.py"],
    deps = [
        ":config",
        requirement("fastapi"),
        requirement("minio"),
    ],
)

py_library(
    name = "config",
    srcs = ["config.py"],
    deps = [
        requirement("pydantic-settings"),
    ],
)

py_console_script_binary(
    name = "main",
    binary_rule = py_binary,
    pkg = requirement("celery"),
    script = "celery",
    deps = [
        ":celery",
        ":tasks",
        requirement("redis"),
    ],
)

py_oci_image(
    name = "image",
    base = "@ubuntu",
    binary = ":main",
    entrypoint = [
        "//src/backend/controller/worker/main",
        "-A",
        "src.backend.controller.worker.tasks",
        "worker",
        "--loglevel",
        "INFO",
    ],
    tars = [":srcs"],
    visibility = ["//src:__subpackages__"],
)

oci_load(
    name = "image.tarball",
    image = ":image",
    repo_tags = ["artemis/backend-controller-worker:latest"],
    visibility = ["//src:__pkg__"],
)
