load("@//tools/testing:pytest.bzl", py_test = "pytest_test")
load("@pip//:requirements.bzl", "requirement")

py_test(
    name = "test_otel",
    srcs = ["test_otel.py"],
    tags = ["unit"],
    deps = [
        "//src/lib/backend:otel",
        requirement("fastapi"),
        requirement("httpx"),
        requirement("opentelemetry-api"),
        requirement("opentelemetry-sdk"),
        requirement("pytest"),
        requirement("sqlalchemy"),
    ],
)
