# -------------------------------------
# Copyright (c) 2025, Dror Kabely
# -------------------------------------
#
# gazelle:python_root

load("@aspect_bazel_lib//lib:transitions.bzl", "platform_transition_filegroup")
load("@aspect_bazel_lib//lib:tar.bzl", "tar")
load("@rules_oci//oci:defs.bzl", oci_load = "oci_tarball", "oci_push")
load("//tools/oci:py_layer.bzl", "py_oci_image")
load("@aspect_rules_py//py:defs.bzl", "py_binary", "py_library")
load("@pip//:requirements.bzl", "requirement")
load("//tools:uvicorn.bzl", "uvicorn_dev_server")

default_visibility = ["//visibility:private"]

# Equivalent to cmdline:
#  `uvicorn main:app --host localhost --port 8002`
uvicorn_dev_server(
    name = "dev",
    args = [
        "main:app",
        "--host",
        "localhost",
        "--port",
        "9002",
        "--reload",
    ],
    imports = ["."],
    data = ["//:.env"],
    visibility = ["//visibility:public"],
    deps = [
        ":backend-main",
    ],
)


py_library(
    name = "backend-main",
    srcs = [
        "__init__.py",
        "main.py",
    ],
    # main = "main.py",
    imports = ["."],
    deps = [
        requirement("fastapi"),
        requirement("sqlalchemy"),
        requirement("sqlalchemy-utils"),
        requirement("python-multipart"),
    ]
)

tar(
    name = "env",
    srcs = ["//:.env"],
)

py_oci_image(
    name = "image",
    base = "@ubuntu",
    binary = ":dev",
    entrypoint = [
        "/src/backend/dev",
        "main:app",
        "--host",
        "0.0.0.0",  # this should allow connections from host
        "--port",
        "9002",
    ],
    exposed_ports = ["9002"],
    tars = [
        ":env"
    ],
)


# $ bazel run //hello_world:tarball
# $ docker run --rm gcr.io/oci_python_hello_world:latest
oci_load(
    name = "tarball",
    image = ":image",
    repo_tags = ["celery-ingestion/backend:latest"],
)

oci_push(
    name = "push",
    image = ":image",
    repository = "localhost:5000/celery-ingestion-backend",
    remote_tags = ["latest"]
)