# -------------------------------------
# Copyright (c) 2025, Dror Kabely
# -------------------------------------
#

load("@rules_oci//oci:defs.bzl", "oci_image", oci_load = "oci_tarball", "oci_push")
load("@bazel_skylib//rules:write_file.bzl", "write_file")
load("@aspect_bazel_lib//lib:tar.bzl", "tar", "mtree_spec", "mtree_mutate")
load("@aspect_bazel_lib//lib:testing.bzl", "assert_archive_contains")

filegroup(
    name = "build.all",
    srcs = [
        "//src/backend/indexing/api:image",
        # "//src/backend/indexing/api:worker-image",
    ]
)

# srcs of the custom connects
_SRCS = {
    "qdrant-sink-kafka-connect": ["@qdrant-sink-kafka-connect-1.2.0//:srcs"],
    "http-sink-kafka-connect": ["@aiven-http-sink-kafka-connect-0.9.0//:srcs"]
}

[
    # create a manifest file for each of the connector original sources
    mtree_spec(
        name = "{connector}.mtree".format(connector=connector_name),
        srcs = connector_srcs,
    )
    for connector_name, connector_srcs in _SRCS.items()
]
[
    # change the root path of the sources for each connector
    # 
    # The root path in each manifest file should now point to
    # /usr/share/confluent-hub-components/...
    # 
    # where confluent's Kafka Connect worker will expect to
    # find executable JAR files of the connector
    mtree_mutate(
        name = "cp-{connector}.mtree".format(connector=connector_name),
        mtree = ":{connector}.mtree".format(connector=connector_name),
        package_dir = "usr/share/confluent-hub-components",
    )
    for connector_name, connector_srcs in _SRCS.items()
]
[
    # package the modified tar's srcs as layers for the cp Kafka Connect
    # image
    tar(
        name = "cp-{connector}".format(connector=connector_name),
        mtree = ":cp-{connector}.mtree".format(connector=connector_name),
        srcs = connector_srcs,
        args = [
            "--exclude=*.bazel", 
            "--exclude=WORKSPACE",
        ],
    )
    for connector_name, connector_srcs in _SRCS.items()
]

# package the modified tar's srcs as layers for the cp Kafka Connect
# image
# All packaged connectors should now sit under /usr/share/confluent-hub-components/
# which is where CP's Kafka Connect worker process expects them to be
#
# Information about them will be loaded at start time of the container
# and they will be readily available for instantiation via Kafka Connect's 
# REST API (at port 8083 by default) once the worker is ready and healthy
oci_image(
    name = "venus-cp-kafka-connect",
    base = "@cp-kafka-connect",
    exposed_ports = ["8083"],
    # add the connectors to the image as tar layers
    # they should eventually sit under /usr/share/conluent-hub-components
    tars = [
        ":cp-{connector}".format(connector=connector_name)
        for connector_name in _SRCS.keys()
    ],
)

oci_load(
    name = "venus-cp-kafka-connect.tarball",
    image = ":venus-cp-kafka-connect",
    repo_tags = ["celery-ingestion/kafka-connect:latest"]
)