# -------------------------------------
# Copyright (c) 2026, Dror Kabely
# -------------------------------------
#

load("@aspect_rules_py//py:defs.bzl", "py_library")
load("@pip//:requirements.bzl", "requirement")

package(
    default_visibility = [
        "//src:__subpackages__",
        "//tests:__subpackages__",
    ],
)

py_library(
    name = "pkg",
    srcs = [
        "__init__.py",
    ],
    deps = [
        ":huggingface",
        ":late_interaction",
        ":sparse",
    ],
)

py_library(
    name = "late_interaction",
    srcs = [
        "late_interaction.py",
    ],
    deps = [
        requirement("httpx"),
    ],
)

py_library(
    name = "sparse",
    srcs = [
        "sparse.py",
    ],
    deps = [
        requirement("fastembed"),
        requirement("langchain-qdrant"),
    ],
)

py_library(
    name = "huggingface",
    srcs = [
        "huggingface.py",
    ],
    deps = [
        requirement("aiohttp"),
        requirement("huggingface-hub"),
        requirement("langchain-core"),
        requirement("numpy"),
        requirement("pydantic"),
        requirement("typing-extensions"),
    ],
)
