# -------------------------------------
# Copyright (c) 2026, Dror Kabely
# -------------------------------------
#

load("@//tools/testing:pytest.bzl", py_test = "pytest_test")
load("@pip//:requirements.bzl", "requirement")

package(default_visibility = ["//visibility:private"])

py_test(
    name = "test_simple",
    srcs = ["test_simple.py"],
    env = {},
    tags = ["unit"],
    deps = [
        "//src/lib/core/ingestion:types",
        "//src/lib/core/ingestion/upserter:pkg",
        "//tests/lib/core/ingestion:conftest",
        requirement("langchain"),
        requirement("langchain-core"),
        requirement("psycopg"),
        requirement("pytest"),
        requirement("pytest-asyncio"),
    ],
)

py_test(
    name = "test_semi_structured",
    srcs = ["test_semi_structured.py"],
    env = {},
    tags = ["unit"],
    deps = [
        "//src/lib/core/ingestion:types",
        "//src/lib/core/ingestion/upserter:pkg",
        "//tests/lib/core/ingestion:conftest",
        requirement("langchain-core"),
        requirement("pytest"),
        requirement("pytest-asyncio"),
    ],
)
