# -------------------------------------
# Copyright (c) 2026, Dror Kabely
# -------------------------------------
#

load("@aspect_rules_py//py:defs.bzl", "py_library")
load("@pip//:requirements.bzl", "requirement")

package(default_visibility = [
    "//src:__subpackages__",
    "//tests:__subpackages__",
])

py_library(
    name = "pkg",
    srcs = [
        "__init__.py",
    ],
    deps = [
        ":base",
        ":qdrant",
        ":semi_structured",
        ":simple",
    ],
)

py_library(
    name = "base",
    srcs = [
        "base.py",
    ],
    deps = [
        requirement("langchain"),
        requirement("langchain_core"),
    ],
)

py_library(
    name = "simple",
    srcs = [
        "simple.py",
    ],
    deps = [
        requirement("langchain"),
        requirement("langchain_core"),
        requirement("typing_extensions"),
    ],
)

py_library(
    name = "semi_structured",
    srcs = [
        "semi_structured.py",
    ],
    deps = [
        requirement("langchain"),
        requirement("langchain_core"),
        requirement("typing_extensions"),
    ],
)

py_library(
    name = "qdrant",
    srcs = [
        "qdrant.py",
    ],
    deps = [
        "//src/lib/core/adapters/vectorstore:qdrant",
        "//src/lib/core/retrieval:params",
        requirement("langchain_core"),
    ],
)
