# -------------------------------------
# Copyright (c) 2026, Dror Kabely
# -------------------------------------
#

load("@aspect_rules_py//py:defs.bzl", "py_library")
load("@pip//:requirements.bzl", "requirement")

package(default_visibility = ["//visibility:private"])

py_library(
    name = "pkg",
    srcs = [
        "__init__.py",
    ],
    visibility = ["//visibility:public"],
    deps = [
        ":base",
        ":semi_structured",
        ":simple",
    ],
)

py_library(
    name = "base",
    srcs = [
        "base.py",
    ],
    deps = [
        requirement("langchain"),
        requirement("langchain_core"),
    ],
)

py_library(
    name = "simple",
    srcs = [
        "simple.py",
    ],
    deps = [
        requirement("langchain"),
        requirement("langchain_core"),
        requirement("typing_extensions"),
    ],
)

py_library(
    name = "semi_structured",
    srcs = [
        "semi_structured.py",
    ],
    deps = [
        requirement("langchain"),
        requirement("langchain_core"),
        requirement("typing_extensions"),
    ],
)
