load("@//tools/testing:pytest.bzl", py_test = "pytest_test")
load("@aspect_rules_py//py:defs.bzl", "py_library")
load("@pip//:requirements.bzl", "requirement")

py_library(
    name = "conftest",
    srcs = ["conftest.py"],
    visibility = ["//visibility:public"],
    deps = [
        "//src/backend/indexing/api:utils",
        requirement("pytest"),
    ],
)

py_test(
    name = "test_ingest",
    srcs = ["test_ingest.py"],
    deps = [
        ":conftest",
        "//src/backend/indexing/api:dependencies",
        "//src/backend/indexing/api:main",
        "//src/lib/core/adapters/stores/memory:blob",
        "//src/lib/core/ingestion:exceptions",
        "//src/lib/core/ingestion:types",
        "//src/lib/core/ingestion/pipeline:parent_page",
        requirement("pytest"),
    ],
)
