# -------------------------------------
# Copyright (c) 2026, Dror Kabely
# -------------------------------------

load("@//tools/testing:pytest.bzl", py_test = "pytest_test")
load("@pip//:requirements.bzl", "requirement")

py_test(
    name = "test_client",
    srcs = ["test_client.py"],
    env = {
        "GATEWAY_URL": "http://gateway-test:9080",
    },
    tags = ["unit"],
    deps = [
        "//src/backend/enterprise/data_sources/api/sources:schemas",
        "//src/backend/storage/api/files:schemas",
        "//src/cli:client",
        "//src/cli:settings",
        requirement("httpx"),
        requirement("pytest"),
        requirement("pytest-asyncio"),
        requirement("respx"),
    ],
)

py_test(
    name = "test_cli",
    srcs = ["test_cli.py"],
    env = {
        "GATEWAY_URL": "http://gateway-test:9080",
    },
    tags = ["unit"],
    deps = [
        "//src/backend/enterprise/data_sources/api/sources:schemas",
        "//src/cli:client",
        "//src/cli:main",
        "//src/cli:settings",
        requirement("click"),
        requirement("pytest"),
        requirement("pytest-asyncio"),
    ],
)
