# -------------------------------------
# Copyright (c) 2026, Dror Kabely
# -------------------------------------

load("@aspect_rules_py//py:defs.bzl", "py_library")
load("@pip//:requirements.bzl", "requirement")

package(
    default_visibility = [
        "//src:__subpackages__",
        "//tests/backend/storage/api:__subpackages__",
        "//tests/cli:__subpackages__",
    ],
)

py_library(
    name = "pkg",
    srcs = [
        "__init__.py",
    ],
    deps = [
        ":router",
    ],
)

py_library(
    name = "router",
    srcs = [
        "router.py",
    ],
    deps = [
        ":schemas",
        ":service",
        "//src/backend/storage/api:config",
        "//src/backend/storage/api:dependencies",
        "//src/lib/backend/logging:pkg",
        requirement("fastapi"),
        requirement("python-multipart"),
    ],
)

py_library(
    name = "service",
    srcs = [
        "service.py",
    ],
    deps = [
        ":exceptions",
        "//src/backend/storage/api:models",
        "//src/backend/storage/api:service",
        "//src/backend/storage/api:tombstone",
        "//src/lib/core/ingestion:contract",
        requirement("minio"),
        requirement("opentelemetry-api"),
        requirement("sqlalchemy"),
    ],
)

py_library(
    name = "exceptions",
    srcs = [
        "exceptions.py",
    ],
    deps = [
        requirement("fastapi"),
    ],
)

py_library(
    name = "schemas",
    srcs = [
        "schemas.py",
    ],
    deps = [
        requirement("pydantic"),
    ],
)
