# -------------------------------------
# Copyright (c) 2026, Dror Kabely
# -------------------------------------
#
# gazelle:python_root

load("@aspect_rules_py//py:defs.bzl", "py_library")
load("@pip//:requirements.bzl", "requirement")
load("@rules_oci//oci:defs.bzl", oci_load = "oci_tarball")
load("//tools/backend:uvicorn.bzl", "uvicorn_server")
load("//tools/oci:py_layer.bzl", "py_oci_image")
load("//tools/oci:stamped_tags.bzl", "stamped_tags")

package(
    default_visibility = [
        "//src/backend/enterprise/intake/api:__subpackages__",
        "//tests/backend/enterprise/intake:__subpackages__",
    ],
)

ENTERPRISE_INGEST_SERVICE_PORT = "9000"

uvicorn_server(
    name = "server",
    app = "src.backend.enterprise.intake.api.main:app",
    host = "0.0.0.0",
    port = ENTERPRISE_INGEST_SERVICE_PORT,
    deps = [":pkg"],
)

py_library(
    name = "pkg",
    srcs = ["__init__.py"],
    deps = [":main"],
)

API_ROUTER_PKGS = [
    "//src/backend/enterprise/intake/api/health:pkg",
    "//src/backend/enterprise/intake/api/intake:pkg",
]

py_library(
    name = "main",
    srcs = ["main.py"],
    deps = [
        ":dependencies",
        ":utils",
        "//src/backend/enterprise/intake/api/intake:exceptions",
        "//src/lib/backend/api:exceptions",
        "//src/lib/backend/telemetry:pkg",
        requirement("opentelemetry-instrumentation-fastapi"),
        requirement("opentelemetry-instrumentation-httpx"),
        requirement("opentelemetry-instrumentation-sqlalchemy"),
        requirement("fastapi"),
    ] + API_ROUTER_PKGS,
)

py_library(
    name = "dependencies",
    srcs = ["dependencies.py"],
    deps = [
        ":config",
        "//src/lib/backend/db:session",
        requirement("asyncpg"),
        requirement("fastapi"),
        requirement("httpx"),
        requirement("sqlalchemy"),
    ],
)

py_library(
    name = "utils",
    srcs = ["utils.py"],
    deps = [
        ":config",
        "//src/backend/enterprise/intake/api/intake:models",
        "//src/lib/backend/logging:pkg",
        requirement("fastapi"),
        requirement("sqlalchemy"),
    ],
)

py_library(
    name = "config",
    srcs = ["config.py"],
    deps = [
        requirement("pydantic"),
        requirement("pydantic-settings"),
    ],
)

py_oci_image(
    name = "image",
    base = "@ubuntu",
    binary = ":server.dev",
    entrypoint = [
        "/src/backend/enterprise/intake/api/server.dev",
        "src.backend.enterprise.intake.api.main:app",
        "--host",
        "0.0.0.0",
        "--port",
        ENTERPRISE_INGEST_SERVICE_PORT,
    ],
    exposed_ports = [ENTERPRISE_INGEST_SERVICE_PORT],
    visibility = ["//src/backend:__pkg__"],
)

stamped_tags(
    name = "tarball.dev.tags",
    dev_tags = ["dev"],
    repository = "artemis/backend-enterprise-intake",
)

oci_load(
    name = "tarball.dev",
    image = ":image",
    repo_tags = ":tarball.dev.tags",
    visibility = ["//src:__pkg__"],
)
