load("@//tools/testing:pytest.bzl", py_test = "pytest_test")
load("@pip//:requirements.bzl", "requirement")

py_test(
    name = "test_loaders",
    srcs = ["test_loaders.py"],
    env = {"HF_HOME": "/tmp/hf_cache"},
    tags = ["unit"],
    deps = [
        "//src/lib/core/adapters/loaders:config",
        "//src/lib/core/adapters/loaders:pymupdf4llm",
        requirement("langchain-core"),
        requirement("pytest"),
        requirement("pymupdf4llm"),
    ],
)
