load("@//tools/testing:pytest.bzl", py_test = "pytest_test")
load("@aspect_rules_py//py:defs.bzl", "py_library")
load("@pip//:requirements.bzl", "requirement")

py_library(
    name = "pkg",
    srcs = ["__init__.py"],
    visibility = ["//visibility:public"],
)

py_library(
    name = "conftest",
    testonly = True,
    srcs = ["conftest.py"],
    deps = [
        requirement("psycopg"),
        requirement("pytest"),
        requirement("testcontainers"),
    ],
)

py_test(
    name = "test_migrations",
    srcs = ["test_migrations.py"],
    data = ["//src/backend/alembic:tarball.dev"],
    tags = ["integration"],
    deps = [
        ":conftest",
        requirement("psycopg"),
        requirement("pytest"),
        requirement("testcontainers"),
    ],
)
