# -------------------------------------
# Copyright (c) 2026, Dror Kabely
# -------------------------------------

load("@aspect_rules_py//py:defs.bzl", "py_library")

package(
    default_visibility = [
        "//src/cli/tui:__subpackages__",
        "//tests/cli:__subpackages__",
    ],
)

py_library(
    name = "status_badge",
    srcs = ["status_badge.py"],
)
