# -------------------------------------
# Copyright (c) 2026, Dror Kabely
# -------------------------------------

load("@aspect_rules_py//py:defs.bzl", "py_library")
load("@pip//:requirements.bzl", "requirement")

package(
    default_visibility = [
        "//src/cli:__pkg__",
        "//tests/cli:__subpackages__",
    ],
)

py_library(
    name = "app",
    srcs = ["app.py"],
    data = ["artemis.tcss"],
    deps = [
        "//src/cli/tui/screens:connectors",
        "//src/cli/tui/screens:create",
        "//src/cli/tui/screens:detail",
        "//src/cli/tui/screens:health",
        "//src/cli/tui/screens:home",
        "//src/cli/tui/screens:objects",
        requirement("textual"),
    ],
)
