# -------------------------------------
# Copyright (c) 2025, Dror Kabely
# -------------------------------------
#
# gazelle:python_root

load("@aspect_rules_py//py:defs.bzl", "py_library")
load("@pip//:requirements.bzl", "requirement")

package(
    default_visibility = [
        "//src/backend:__subpackages__",
        "//src/lib/core:__subpackages__",
        "//tests/backend:__subpackages__",
        "//tests/lib/core:__subpackages__",
    ],
)

py_library(
    name = "pkg",
    srcs = [
        "__init__.py",
    ],
    deps = [
        ":config",
        ":exceptions",
        ":types",
        "//src/lib/core/ingestion/indexer:pkg",
        "//src/lib/core/ingestion/normalizer:pkg",
        "//src/lib/core/ingestion/pipeline:pkg",
        "//src/lib/core/ingestion/upserter:pkg",
    ],
)

py_library(
    name = "config",
    srcs = [
        "config.py",
    ],
    deps = [
        "//src/lib/core/ingestion/indexer:pkg",
        "//src/lib/core/ingestion/normalizer:pkg",
        "//src/lib/core/ingestion/pipeline:pkg",
        "//src/lib/core/ingestion/upserter:pkg",
        "//src/lib/core/retrieval/adapters:pkg",
        requirement("langchain"),
        requirement("langchain-core"),
    ],
)

py_library(
    name = "types",
    srcs = [
        "types.py",
    ],
    deps = [
        requirement("langchain-core"),
        requirement("pydantic"),
    ],
)

py_library(
    name = "exceptions",
    srcs = [
        "exceptions.py",
    ],
)
