load("@aspect_rules_py//py:defs.bzl", "py_library")
load("@pip//:requirements.bzl", "requirement")

py_library(
    name = "service",
    srcs = ["service.py"],
    visibility = ["//visibility:public"],
    deps = [
        "//src/backend/indexing/api:dependencies",
        "//src/lib/core/ingestion:contract",
        "//src/lib/core/ingestion:pkg",
        "//src/lib/core/ingestion:types",
        "//src/lib/core/ingestion/pipeline:parent_page",
        requirement("fastapi"),
        requirement("langchain-core"),
        requirement("pydantic"),
    ],
)

py_library(
    name = "router",
    srcs = ["router.py"],
    visibility = ["//visibility:public"],
    deps = [
        ":service",
        "//src/backend/indexing/api:dependencies",
        "//src/lib/backend/logging:pkg",
        "//src/lib/core/ingestion:pkg",
        requirement("fastapi"),
        requirement("langchain-core"),
        requirement("opentelemetry-api"),
    ],
)

py_library(
    name = "pkg",
    srcs = ["__init__.py"],
    visibility = ["//visibility:public"],
    deps = [
        ":router",
    ],
)
