# -------------------------------------
# Copyright (c) 2025, Dror Kabely
# -------------------------------------
#
# gazelle:python_root

load("@pip//:requirements.bzl", "requirement")
load("@rules_python//python:defs.bzl", "py_library")

package(default_visibility = [
    "//:__subpackages__",
    "//src:__subpackages__",
])

py_library(
    name = "pkg",
    srcs = [
        "__init__.py",
    ],
    deps = [
        ":config",
        ":docling",
        ":pymupdf4llm",
    ],
)

py_library(
    name = "config",
    srcs = [
        "config.py",
    ],
    deps = [
        ":docling",
        ":pymupdf4llm",
        requirement("langchain-core"),
    ],
)

py_library(
    name = "docling",
    srcs = [
        "docling.py",
    ],
    deps = [
        requirement("docling"),
        requirement("httpx"),
        requirement("langchain-core"),
    ],
)

py_library(
    name = "pymupdf4llm",
    srcs = [
        "pymupdf4llm_.py",
    ],
    deps = [
        requirement("langchain-core"),
        requirement("pymupdf4llm"),
    ],
)
