load("@//tools/testing:pytest.bzl", py_test = "pytest_test")
load("@pip//:requirements.bzl", "requirement")
load("@rules_python//python:defs.bzl", "py_library")

package(default_visibility = ["//visibility:private"])


py_test(
    name = "test_semi_structured",
    srcs = ["test_semi_structured.py"],
    env = {},
    tags = ["unit"],
    deps = [
        "//src/lib/core/ingestion/indexer:semi_structured",
        "//src/lib/core/ingestion:types",
        "//tests/lib/core/ingestion:conftest",
        requirement("langchain_core"),
        requirement("pytest"),
    ],
)

py_test(
    name = "test_simple",
    srcs = ["test_simple.py"],
    env = {},
    tags = ["unit"],
    deps = [
        "//src/lib/core/adapters/vectorstore:qdrant",
        "//src/lib/core/ingestion/indexer:simple",
        "//tests/lib/core/ingestion:conftest",
        requirement("langchain_core"),
        requirement("pytest"),
    ],
)
