load("@//tools/testing:pytest.bzl", py_test = "pytest_test")
load("@aspect_rules_py//py:defs.bzl", "py_library")
load("@pip//:requirements.bzl", "requirement")

py_library(
    name = "conftest",
    testonly = True,
    srcs = ["conftest.py"],
    deps = [
        "//tests/lib/testcontainers:migrations",
        requirement("celery"),
        requirement("minio"),
        requirement("pika"),
        requirement("pytest"),
        requirement("testcontainers"),
    ],
)

py_test(
    name = "test_chain",
    srcs = ["test_chain.py"],
    data = ["//src/backend/alembic:tarball.dev"],
    tags = ["integration"],
    deps = [
        ":conftest",
        requirement("celery"),
        requirement("minio"),
        requirement("pytest"),
        requirement("testcontainers"),
    ],
)
