# -------------------------------------
# Copyright (c) 2026, Dror Kabely
# -------------------------------------
#
# gazelle:python_root

load("@aspect_rules_py//py:defs.bzl", "py_library")
load("@pip//:requirements.bzl", "requirement")
load("@rules_oci//oci:defs.bzl", "oci_push", oci_load = "oci_tarball")
load("//tools/backend:uvicorn.bzl", "uvicorn_server")
load("//tools/oci:py_layer.bzl", "py_oci_image")

package(default_visibility = [
    "//src/backend:__subpackages__",
    "//src/backend/indexing/api:__subpackages__",
    "//tests:__subpackages__",
])

INDEXING_SERVICE_PORT = "10000"

API_ROUTERS = [
    "//src/backend/indexing/api/health:pkg",
    "//src/backend/indexing/api/index:pkg",
    "//src/backend/indexing/api/retrieve:pkg",
]

py_library(
    name = "exceptions",
    srcs = [
        "exceptions.py",
    ],
    deps = [
        "//src/lib/core/ingestion:exceptions",
        requirement("fastapi"),
    ],
)

py_library(
    name = "dependencies",
    srcs = [
        "dependencies.py",
    ],
    deps = [
        ":config",
        "//src/backend/indexing/lib/handler:pkg",
        "//src/lib/core/adapters/embedding:pkg",
        "//src/lib/core/adapters/stores/sql:pkg",
        "//src/lib/core/adapters/vectorstore:pkg",
        "//src/lib/core/ingestion:pkg",
        requirement("asyncpg"),
        requirement("fastembed"),
        requirement("fastapi"),
        requirement("httpx"),
        requirement("langchain"),
        requirement("langchain-core"),
        requirement("langchain-qdrant"),
        requirement("qdrant-client"),
        requirement("sqlalchemy"),
    ],
)

py_library(
    name = "config",
    srcs = [
        "config.py",
    ],
    visibility = ["//src/backend/indexing/api:__subpackages__"],
    deps = [
        "//src/lib/core/adapters/vectorstore:pkg",
        "//src/lib/core/ingestion:config",
        requirement("pydantic"),
        requirement("pydantic-settings"),
    ],
)

py_library(
    name = "utils",
    srcs = [
        "utils.py",
    ],
    deps = [
        ":config",
        ":dependencies",
        "//src/backend/indexing/api/retrieve:service",
        "//src/lib/backend/logging:pkg",
        "//src/lib/core/adapters/document_compressors/cohere:pkg",
        "//src/lib/core/retrieval/adapters:simple",
        requirement("cohere"),
        requirement("fastapi"),
    ],
)

py_library(
    name = "main",
    srcs = [
        "__init__.py",
        "main.py",
    ],
    imports = ["."],
    deps = [
        ":exceptions",
        ":utils",
        "//src/lib/backend/api:pkg",
        requirement("fastapi"),
    ] + API_ROUTERS,
)

# Main FastAPI entrypoint
#
# Creates two targets:
# 1. apollo-indexing.dev: Development server (Uvicorn)
# 2. apollo-indexing:     Deployment server (Gunicorn)
uvicorn_server(
    name = "artemis-indexing",
    app = "src.backend.indexing.api.main:app",
    host = "0.0.0.0",
    port = INDEXING_SERVICE_PORT,
    deps = [
        ":main",
    ],
)

py_oci_image(
    name = "image.dev",
    base = "//tools/oci/images/ubuntu:noble",
    binary = ":artemis-indexing.dev",
    entrypoint = [
        "/src/backend/indexing/api/artemis-indexing.dev",
        "src.backend.indexing.api.main:app",
        "--host",
        "0.0.0.0",  # this should allow connections from host
        "--port",
        INDEXING_SERVICE_PORT,
        "--reload",
    ],
    exposed_ports = [INDEXING_SERVICE_PORT],
    visibility = ["//src/backend:__pkg__"],
)

# $ bazel run //src/backend/indexing/api:tarball.dev
oci_load(
    name = "tarball.dev",
    image = ":image.dev",
    repo_tags = ["artemis/backend-indexing:dev"],
    visibility = ["//src:__pkg__"],
)

oci_push(
    name = "push.dev",
    image = ":image.dev",
    remote_tags = ["dev"],
    repository = "localhost:5000/artemis-backend-indexing",
)
