# -------------------------------------
# Copyright (c) 2026, Dror Kabely
# -------------------------------------
#

load("@//tools/testing:pytest.bzl", py_test = "pytest_test")
load("@aspect_rules_py//py:defs.bzl", "py_library")
load("@pip//:requirements.bzl", "requirement")

package(
    default_visibility = ["//visibility:private"],
)

py_test(
    name = "test_params",
    srcs = [
        "__init__.py",
        "test_params.py",
    ],
    tags = ["unit"],
    deps = [
        "//src/lib/core/retrieval:params",
        requirement("pytest"),
        requirement("qdrant-client"),
    ],
)

py_library(
    name = "conftest",
    testonly = True,
    srcs = ["conftest.py"],
    visibility = ["//visibility:private"],
    deps = [
        "//src/lib/core/adapters/document_compressors/cohere:pkg",
        "//src/lib/core/adapters/embedding:huggingface",
        "//src/lib/core/adapters/vectorstore:qdrant",
        "//tests/lib/testcontainers/tei:pkg",
        "//tests/lib/testcontainers/vllm:pkg",
        requirement("cohere"),
        requirement("langchain-core"),
        requirement("pytest"),
        requirement("qdrant-client"),
        requirement("testcontainers"),
    ],
)

py_test(
    name = "test_parent_page",
    srcs = [
        "__init__.py",
        "test_parent_page.py",
    ],
    tags = ["unit"],
    deps = [
        "//src/lib/core/retrieval:parent_page",
        requirement("langchain"),
        requirement("langchain-core"),
        requirement("pytest"),
        requirement("pytest-asyncio"),
    ],
)

py_test(
    name = "test_namespace_retriever",
    srcs = [
        "__init__.py",
        "test_namespace_retriever.py",
    ],
    tags = ["integration"],
    deps = [
        ":conftest",
        "//src/backend/indexing/api/retrieve:retriever",
        "//src/lib/core/adapters/document_compressors/cohere:pkg",
        "//src/lib/core/adapters/vectorstore:qdrant",
        "//src/lib/core/retrieval/adapters:simple",
        requirement("langchain-core"),
        requirement("pytest"),
    ],
)
